version: "3.8"

services:
  utila-music-bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/app:ro
    healthcheck:
      test: ["CMD-SHELL", "python -c \"print('ok')\""]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
